OTC-303: Additional filters handling
openimis/openimis-fe-insuree_js pull request #15
Opened 2021-07-05 07:27 UTC by dborowiecki

TICKET: [OTC-303](https://openimis.atlassian.net/browse/OTC-303)

2021-07-05 14:36 UTC, dragos-dobre requested changes

2021-07-05 14:36 UTC, dragos-dobre commented on src/components/FamilySearcher.js
> +        console.log("Family action contrib key:", actionsContributionKey)
Is this for debugging? Do we need this?

2021-07-06 08:18 UTC, dborowiecki commented on src/components/FamilySearcher.js
> +        console.log("Family action contrib key:", actionsContributionKey)
It was for debugging, removed.

2021-07-06 11:40 UTC, dragos-dobre approved these changes

2021-07-06 11:40 UTC, merged