ONI-3: Added insuree status dropdown.
openimis/openimis-fe-insuree_js pull request #91
Opened 2023-09-25 23:03 UTC by wzglinieckisoldevelo

Ticket: https://openimis.atlassian.net/browse/ONI-3

Changes:
- Added fields for insuree status/date of status/reason of status

2023-09-27 06:44 UTC, olewandowski1 commented on src/components/InsureeMasterPanel.js
> +                      }}
No need to wrap it in ' { } '.
`
                      onChange={(v) => this.updateAttributes({ "status": v, "statusReason": null })}
`

2023-09-27 06:46 UTC, olewandowski1 commented on src/pickers/InsureeStatusDatePicker.js
> +import { INSUREE_STATUS } from "../constants";
Remember about organizing imports into three sections (external libraries, ui, internal files).

2023-09-27 06:46 UTC, olewandowski1 commented on src/pickers/InsureeStatusDatePicker.js
> +  const { formatMessage } = useTranslations("insuree", modulesManager);
Use MODULE_NAME from constants instead of raw string

2023-09-27 06:47 UTC, olewandowski1 commented on src/pickers/InsureeStatusPicker.js
> +import { INSUREE_STATUS } from "../constants";
Remember about organizing imports

2023-09-27 06:47 UTC, olewandowski1 commented on src/pickers/InsureeStatusReasonPicker.js
> +import _debounce from "lodash/debounce";
Remember about organizing imports

2023-09-27 06:51 UTC, olewandowski1 commented on src/pickers/InsureeStatusReasonPicker.js
> +    props;
Props can be destructed like this:
`
const InsureeStatusReasonPicker = ({
onChange,
readOnly,
required,
value, 
filterOptions,
filterSelectedOptions,
multiple,
extraFragment,
edited,
}) => {...}
`

2023-09-27 06:52 UTC, olewandowski1 commented on src/pickers/InsureeStatusReasonPicker.js
> +  const { formatMessage } = useTranslations("insuree", modulesManager);
Use MODULE_NAME from constants instead of raw string.

2023-09-27 06:53 UTC, olewandowski1 requested changes
@wzglinieckisoldevelo I left some comments.

2023-10-02 11:42 UTC, olewandowski1 commented on src/pickers/InsureeStatusDatePicker.js
> +      onChange={(p) => updateAttribute("insureeStatusDate", p)}
Could you use more explicit naming instead of 'p'?

2023-10-02 11:43 UTC, olewandowski1 commented on src/pickers/InsureeStatusReasonPicker.js
> +      onChange={(v) => onChange(v, v ? `${v.code} ${v.insureeStatusReason}` : null)}
Could you use more explicit naming instead of 'v'?

2023-10-02 12:03 UTC, dborowiecki approved these changes

2023-10-02 13:32 UTC, merged